# Generated by Django 5.1.4 on 2024-12-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='studentEmail',
            field=models.CharField(default='temp@example.com', max_length=30, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='student',
            name='studentMobile',
            field=models.CharField(default=1234, max_length=10, verbose_name='Mobile'),
        ),
        migrations.AddField(
            model_name='student',
            name='studentPassword',
            field=models.CharField(default='123', max_length=50, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentName',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
    ]
