# Generated by Django 5.1.4 on 2024-12-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_student_studentemail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultyName', models.CharField(max_length=50, verbose_name='Name')),
                ('facultyMobile', models.PositiveIntegerField(max_length=10, verbose_name='Number')),
                ('facultyDepartment', models.CharField(max_length=30, verbose_name='Department')),
                ('facultyRegistrationDate', models.DateTimeField(verbose_name='RegistrationDate')),
            ],
        ),
    ]
